### ISSUE TITLE
License needed

### ISSUE THREAD

**Issue by jsullivanlive** [TehNrd/sObject-Remote#8]
Can I propose adding a license to the code so that people know what is permissible to do with it?

jQuery uses MIT, but here's a site that makes it easy to pick: http://choosealicense.com

**Comment by tehnrd** [comment]
Done! Thanks for submitting pull request.

**Comment by jsullivanlive** [comment]
No man, thank you

**Comment by tehnrd** [comment]
Sorry took so long, not sure how I missed this.
